/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package fr.placide.cacmerbsmsmovement.domain.avro;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class MovementAvro extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 5662510863186234095L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"MovementAvro\",\"namespace\":\"fr.placide.cacmerbsmsmovement.domain.avro\",\"fields\":[{\"name\":\"mvtId\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"sens\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"amount\",\"type\":\"double\"},{\"name\":\"createdAt\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"accountId\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"account\",\"type\":{\"type\":\"record\",\"name\":\"Account\",\"fields\":[{\"name\":\"accountId\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"type\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"balance\",\"type\":\"double\"},{\"name\":\"overdraft\",\"type\":\"double\"},{\"name\":\"customerId\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"customer\",\"type\":{\"type\":\"record\",\"name\":\"Customer\",\"fields\":[{\"name\":\"customerId\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"firstname\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"lastname\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"createdAt\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"risk\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"status\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}}]}}]}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<MovementAvro> ENCODER =
      new BinaryMessageEncoder<MovementAvro>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<MovementAvro> DECODER =
      new BinaryMessageDecoder<MovementAvro>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<MovementAvro> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<MovementAvro> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<MovementAvro> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<MovementAvro>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this MovementAvro to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a MovementAvro from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a MovementAvro instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static MovementAvro fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.lang.String mvtId;
  private java.lang.String sens;
  private double amount;
  private java.lang.String createdAt;
  private java.lang.String accountId;
  private fr.placide.cacmerbsmsmovement.domain.avro.Account account;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public MovementAvro() {}

  /**
   * All-args constructor.
   * @param mvtId The new value for mvtId
   * @param sens The new value for sens
   * @param amount The new value for amount
   * @param createdAt The new value for createdAt
   * @param accountId The new value for accountId
   * @param account The new value for account
   */
  public MovementAvro(java.lang.String mvtId, java.lang.String sens, java.lang.Double amount, java.lang.String createdAt, java.lang.String accountId, fr.placide.cacmerbsmsmovement.domain.avro.Account account) {
    this.mvtId = mvtId;
    this.sens = sens;
    this.amount = amount;
    this.createdAt = createdAt;
    this.accountId = accountId;
    this.account = account;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return mvtId;
    case 1: return sens;
    case 2: return amount;
    case 3: return createdAt;
    case 4: return accountId;
    case 5: return account;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: mvtId = value$ != null ? value$.toString() : null; break;
    case 1: sens = value$ != null ? value$.toString() : null; break;
    case 2: amount = (java.lang.Double)value$; break;
    case 3: createdAt = value$ != null ? value$.toString() : null; break;
    case 4: accountId = value$ != null ? value$.toString() : null; break;
    case 5: account = (fr.placide.cacmerbsmsmovement.domain.avro.Account)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'mvtId' field.
   * @return The value of the 'mvtId' field.
   */
  public java.lang.String getMvtId() {
    return mvtId;
  }


  /**
   * Sets the value of the 'mvtId' field.
   * @param value the value to set.
   */
  public void setMvtId(java.lang.String value) {
    this.mvtId = value;
  }

  /**
   * Gets the value of the 'sens' field.
   * @return The value of the 'sens' field.
   */
  public java.lang.String getSens() {
    return sens;
  }


  /**
   * Sets the value of the 'sens' field.
   * @param value the value to set.
   */
  public void setSens(java.lang.String value) {
    this.sens = value;
  }

  /**
   * Gets the value of the 'amount' field.
   * @return The value of the 'amount' field.
   */
  public double getAmount() {
    return amount;
  }


  /**
   * Sets the value of the 'amount' field.
   * @param value the value to set.
   */
  public void setAmount(double value) {
    this.amount = value;
  }

  /**
   * Gets the value of the 'createdAt' field.
   * @return The value of the 'createdAt' field.
   */
  public java.lang.String getCreatedAt() {
    return createdAt;
  }


  /**
   * Sets the value of the 'createdAt' field.
   * @param value the value to set.
   */
  public void setCreatedAt(java.lang.String value) {
    this.createdAt = value;
  }

  /**
   * Gets the value of the 'accountId' field.
   * @return The value of the 'accountId' field.
   */
  public java.lang.String getAccountId() {
    return accountId;
  }


  /**
   * Sets the value of the 'accountId' field.
   * @param value the value to set.
   */
  public void setAccountId(java.lang.String value) {
    this.accountId = value;
  }

  /**
   * Gets the value of the 'account' field.
   * @return The value of the 'account' field.
   */
  public fr.placide.cacmerbsmsmovement.domain.avro.Account getAccount() {
    return account;
  }


  /**
   * Sets the value of the 'account' field.
   * @param value the value to set.
   */
  public void setAccount(fr.placide.cacmerbsmsmovement.domain.avro.Account value) {
    this.account = value;
  }

  /**
   * Creates a new MovementAvro RecordBuilder.
   * @return A new MovementAvro RecordBuilder
   */
  public static fr.placide.cacmerbsmsmovement.domain.avro.MovementAvro.Builder newBuilder() {
    return new fr.placide.cacmerbsmsmovement.domain.avro.MovementAvro.Builder();
  }

  /**
   * Creates a new MovementAvro RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new MovementAvro RecordBuilder
   */
  public static fr.placide.cacmerbsmsmovement.domain.avro.MovementAvro.Builder newBuilder(fr.placide.cacmerbsmsmovement.domain.avro.MovementAvro.Builder other) {
    if (other == null) {
      return new fr.placide.cacmerbsmsmovement.domain.avro.MovementAvro.Builder();
    } else {
      return new fr.placide.cacmerbsmsmovement.domain.avro.MovementAvro.Builder(other);
    }
  }

  /**
   * Creates a new MovementAvro RecordBuilder by copying an existing MovementAvro instance.
   * @param other The existing instance to copy.
   * @return A new MovementAvro RecordBuilder
   */
  public static fr.placide.cacmerbsmsmovement.domain.avro.MovementAvro.Builder newBuilder(fr.placide.cacmerbsmsmovement.domain.avro.MovementAvro other) {
    if (other == null) {
      return new fr.placide.cacmerbsmsmovement.domain.avro.MovementAvro.Builder();
    } else {
      return new fr.placide.cacmerbsmsmovement.domain.avro.MovementAvro.Builder(other);
    }
  }

  /**
   * RecordBuilder for MovementAvro instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<MovementAvro>
    implements org.apache.avro.data.RecordBuilder<MovementAvro> {

    private java.lang.String mvtId;
    private java.lang.String sens;
    private double amount;
    private java.lang.String createdAt;
    private java.lang.String accountId;
    private fr.placide.cacmerbsmsmovement.domain.avro.Account account;
    private fr.placide.cacmerbsmsmovement.domain.avro.Account.Builder accountBuilder;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(fr.placide.cacmerbsmsmovement.domain.avro.MovementAvro.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.mvtId)) {
        this.mvtId = data().deepCopy(fields()[0].schema(), other.mvtId);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.sens)) {
        this.sens = data().deepCopy(fields()[1].schema(), other.sens);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.amount)) {
        this.amount = data().deepCopy(fields()[2].schema(), other.amount);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.createdAt)) {
        this.createdAt = data().deepCopy(fields()[3].schema(), other.createdAt);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.accountId)) {
        this.accountId = data().deepCopy(fields()[4].schema(), other.accountId);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
      if (isValidValue(fields()[5], other.account)) {
        this.account = data().deepCopy(fields()[5].schema(), other.account);
        fieldSetFlags()[5] = other.fieldSetFlags()[5];
      }
      if (other.hasAccountBuilder()) {
        this.accountBuilder = fr.placide.cacmerbsmsmovement.domain.avro.Account.newBuilder(other.getAccountBuilder());
      }
    }

    /**
     * Creates a Builder by copying an existing MovementAvro instance
     * @param other The existing instance to copy.
     */
    private Builder(fr.placide.cacmerbsmsmovement.domain.avro.MovementAvro other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.mvtId)) {
        this.mvtId = data().deepCopy(fields()[0].schema(), other.mvtId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.sens)) {
        this.sens = data().deepCopy(fields()[1].schema(), other.sens);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.amount)) {
        this.amount = data().deepCopy(fields()[2].schema(), other.amount);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.createdAt)) {
        this.createdAt = data().deepCopy(fields()[3].schema(), other.createdAt);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.accountId)) {
        this.accountId = data().deepCopy(fields()[4].schema(), other.accountId);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.account)) {
        this.account = data().deepCopy(fields()[5].schema(), other.account);
        fieldSetFlags()[5] = true;
      }
      this.accountBuilder = null;
    }

    /**
      * Gets the value of the 'mvtId' field.
      * @return The value.
      */
    public java.lang.String getMvtId() {
      return mvtId;
    }


    /**
      * Sets the value of the 'mvtId' field.
      * @param value The value of 'mvtId'.
      * @return This builder.
      */
    public fr.placide.cacmerbsmsmovement.domain.avro.MovementAvro.Builder setMvtId(java.lang.String value) {
      validate(fields()[0], value);
      this.mvtId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'mvtId' field has been set.
      * @return True if the 'mvtId' field has been set, false otherwise.
      */
    public boolean hasMvtId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'mvtId' field.
      * @return This builder.
      */
    public fr.placide.cacmerbsmsmovement.domain.avro.MovementAvro.Builder clearMvtId() {
      mvtId = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'sens' field.
      * @return The value.
      */
    public java.lang.String getSens() {
      return sens;
    }


    /**
      * Sets the value of the 'sens' field.
      * @param value The value of 'sens'.
      * @return This builder.
      */
    public fr.placide.cacmerbsmsmovement.domain.avro.MovementAvro.Builder setSens(java.lang.String value) {
      validate(fields()[1], value);
      this.sens = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'sens' field has been set.
      * @return True if the 'sens' field has been set, false otherwise.
      */
    public boolean hasSens() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'sens' field.
      * @return This builder.
      */
    public fr.placide.cacmerbsmsmovement.domain.avro.MovementAvro.Builder clearSens() {
      sens = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'amount' field.
      * @return The value.
      */
    public double getAmount() {
      return amount;
    }


    /**
      * Sets the value of the 'amount' field.
      * @param value The value of 'amount'.
      * @return This builder.
      */
    public fr.placide.cacmerbsmsmovement.domain.avro.MovementAvro.Builder setAmount(double value) {
      validate(fields()[2], value);
      this.amount = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'amount' field has been set.
      * @return True if the 'amount' field has been set, false otherwise.
      */
    public boolean hasAmount() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'amount' field.
      * @return This builder.
      */
    public fr.placide.cacmerbsmsmovement.domain.avro.MovementAvro.Builder clearAmount() {
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'createdAt' field.
      * @return The value.
      */
    public java.lang.String getCreatedAt() {
      return createdAt;
    }


    /**
      * Sets the value of the 'createdAt' field.
      * @param value The value of 'createdAt'.
      * @return This builder.
      */
    public fr.placide.cacmerbsmsmovement.domain.avro.MovementAvro.Builder setCreatedAt(java.lang.String value) {
      validate(fields()[3], value);
      this.createdAt = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'createdAt' field has been set.
      * @return True if the 'createdAt' field has been set, false otherwise.
      */
    public boolean hasCreatedAt() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'createdAt' field.
      * @return This builder.
      */
    public fr.placide.cacmerbsmsmovement.domain.avro.MovementAvro.Builder clearCreatedAt() {
      createdAt = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'accountId' field.
      * @return The value.
      */
    public java.lang.String getAccountId() {
      return accountId;
    }


    /**
      * Sets the value of the 'accountId' field.
      * @param value The value of 'accountId'.
      * @return This builder.
      */
    public fr.placide.cacmerbsmsmovement.domain.avro.MovementAvro.Builder setAccountId(java.lang.String value) {
      validate(fields()[4], value);
      this.accountId = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'accountId' field has been set.
      * @return True if the 'accountId' field has been set, false otherwise.
      */
    public boolean hasAccountId() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'accountId' field.
      * @return This builder.
      */
    public fr.placide.cacmerbsmsmovement.domain.avro.MovementAvro.Builder clearAccountId() {
      accountId = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'account' field.
      * @return The value.
      */
    public fr.placide.cacmerbsmsmovement.domain.avro.Account getAccount() {
      return account;
    }


    /**
      * Sets the value of the 'account' field.
      * @param value The value of 'account'.
      * @return This builder.
      */
    public fr.placide.cacmerbsmsmovement.domain.avro.MovementAvro.Builder setAccount(fr.placide.cacmerbsmsmovement.domain.avro.Account value) {
      validate(fields()[5], value);
      this.accountBuilder = null;
      this.account = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'account' field has been set.
      * @return True if the 'account' field has been set, false otherwise.
      */
    public boolean hasAccount() {
      return fieldSetFlags()[5];
    }

    /**
     * Gets the Builder instance for the 'account' field and creates one if it doesn't exist yet.
     * @return This builder.
     */
    public fr.placide.cacmerbsmsmovement.domain.avro.Account.Builder getAccountBuilder() {
      if (accountBuilder == null) {
        if (hasAccount()) {
          setAccountBuilder(fr.placide.cacmerbsmsmovement.domain.avro.Account.newBuilder(account));
        } else {
          setAccountBuilder(fr.placide.cacmerbsmsmovement.domain.avro.Account.newBuilder());
        }
      }
      return accountBuilder;
    }

    /**
     * Sets the Builder instance for the 'account' field
     * @param value The builder instance that must be set.
     * @return This builder.
     */

    public fr.placide.cacmerbsmsmovement.domain.avro.MovementAvro.Builder setAccountBuilder(fr.placide.cacmerbsmsmovement.domain.avro.Account.Builder value) {
      clearAccount();
      accountBuilder = value;
      return this;
    }

    /**
     * Checks whether the 'account' field has an active Builder instance
     * @return True if the 'account' field has an active Builder instance
     */
    public boolean hasAccountBuilder() {
      return accountBuilder != null;
    }

    /**
      * Clears the value of the 'account' field.
      * @return This builder.
      */
    public fr.placide.cacmerbsmsmovement.domain.avro.MovementAvro.Builder clearAccount() {
      account = null;
      accountBuilder = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public MovementAvro build() {
      try {
        MovementAvro record = new MovementAvro();
        record.mvtId = fieldSetFlags()[0] ? this.mvtId : (java.lang.String) defaultValue(fields()[0]);
        record.sens = fieldSetFlags()[1] ? this.sens : (java.lang.String) defaultValue(fields()[1]);
        record.amount = fieldSetFlags()[2] ? this.amount : (java.lang.Double) defaultValue(fields()[2]);
        record.createdAt = fieldSetFlags()[3] ? this.createdAt : (java.lang.String) defaultValue(fields()[3]);
        record.accountId = fieldSetFlags()[4] ? this.accountId : (java.lang.String) defaultValue(fields()[4]);
        if (accountBuilder != null) {
          try {
            record.account = this.accountBuilder.build();
          } catch (org.apache.avro.AvroMissingFieldException e) {
            e.addParentField(record.getSchema().getField("account"));
            throw e;
          }
        } else {
          record.account = fieldSetFlags()[5] ? this.account : (fr.placide.cacmerbsmsmovement.domain.avro.Account) defaultValue(fields()[5]);
        }
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<MovementAvro>
    WRITER$ = (org.apache.avro.io.DatumWriter<MovementAvro>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<MovementAvro>
    READER$ = (org.apache.avro.io.DatumReader<MovementAvro>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.mvtId);

    out.writeString(this.sens);

    out.writeDouble(this.amount);

    out.writeString(this.createdAt);

    out.writeString(this.accountId);

    this.account.customEncode(out);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.mvtId = in.readString();

      this.sens = in.readString();

      this.amount = in.readDouble();

      this.createdAt = in.readString();

      this.accountId = in.readString();

      if (this.account == null) {
        this.account = new fr.placide.cacmerbsmsmovement.domain.avro.Account();
      }
      this.account.customDecode(in);

    } else {
      for (int i = 0; i < 6; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.mvtId = in.readString();
          break;

        case 1:
          this.sens = in.readString();
          break;

        case 2:
          this.amount = in.readDouble();
          break;

        case 3:
          this.createdAt = in.readString();
          break;

        case 4:
          this.accountId = in.readString();
          break;

        case 5:
          if (this.account == null) {
            this.account = new fr.placide.cacmerbsmsmovement.domain.avro.Account();
          }
          this.account.customDecode(in);
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










